apiVersion: "v1"
name: hlf-k8s
home: https://substra.org/
version: 1.0.0-alpha.8
description: Tolling package for Substra that configure the network
icon: https://avatars1.githubusercontent.com/u/38098422?s=200&v=4
sources:
  - https://github.com/SubstraFoudation/hlf-k8s
maintainers:
  - name: ClementGautier
    email: clement@gautier.im
